import AuthProvider from './components/AuthProvider/AuthProvider'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Box Office',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={`${inter.className} bg-black`}>
      <AuthProvider>
<div className='min-h-screen'>
{children}
</div>
        </AuthProvider>

        </body>

    </html>
  )
}
